<!DOCTYPE html>
	<head>
		<meta charset="UTF-8">
		
		<title>Google Page Speed API</title>
		
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
		<script type="text/javascript">         
		     $(document).ready(function() {
		                jQuery("#check_url").click(function () {
		                     var pageUrl = jQuery("#page_url").val();
		                     jQuery("#check_results").html('<div align="center"><img src="views/images/loading.gif"><br /> Generating page report...</div>');
		                     jQuery.ajax({
		                           type: 'POST',
		                           url: '{script_url}',
		                           data: {              
		                                'page_url' : pageUrl
		                           },
		                           success: function(data) {
		                                        jQuery("#check_results").html(data);
		                                        return;
		                           }
		                     });        
		                     
		                 });
		      });
		</script>
		
		<style>
			body {
			  font-size: 14px;
			  font-family: Helvetica, Arial, sans-serif;
			}			
		
			.error_msg {
				color: red;
			}
			
			#check_results {
				margin-top: 10px;
			}
		</style>
	</head>
	
	<body>
			<h3>Google Pagespeed Checker</h3>
			<p>Enter a URL in the form to get a pagespeed report from the Google page speed API.</p> 
			<div align="center">
				<input type="text" name="page_url" id="page_url"/>
				<br />
				<input type="submit" value="Get Pagespeed" id="check_url" />
				<br />
				<div id="check_results"></div>
			</div>
	</body>
</html>