<table>
	<tr>
		<th>Parameter</th>
		<th>Response</th>		
	</tr>
	
	<tr>
		<td>Page URL</td>
		<td>{page_url}</td>
	</tr>
		
	<tr>
		<td>Page Score</td>
		<td>{page_score}</td>
	</tr>
	
	<tr>
		<td>Resources #</td>
		<td>{total_resources}</td>
	</tr>
	
	<tr>
		<td>Hosts #</td>
		<td>{total_hosts}</td>		
	</tr>

	<tr>
		<td>Requested HTML (bytes)</td>
		<td>{html_bytes}</td>		
	</tr>
		
	<tr>
		<td>Requested CSS (bytes)</td>
		<td>{css_bytes}</td>		
	</tr>	
	
	<tr>
		<td>Requested JS (bytes)</td>
		<td>{js_bytes}</td>		
	</tr>	
	
	<tr>
		<td>Requested images (bytes)</td>
		<td>{image_bytes}</td>		
	</tr>	
</table>